version: '3.3'

services:
  app:
    #image: haskell:latest
    image: gibiansky/ihaskell:latest
    volumes:
       - ./src:/notebooks
       - ./src/stack.yaml:/ihaskell/stack.yaml
    ports:
      - '8888:8888'
    tty: true
  cli:
    image: haskell:latest
    volumes:
       - ./src:/app
    tty: true

volumes:
  data:
    driver: 'local'

