version: '3.3'

services:
  app:
    #image: haskell:latest
    image: gibiansky/ihaskell:latest
    volumes:
       - ./src:/notebooks
    ports:
      - '8888:8888'
    tty: true

volumes:
  data:
    driver: 'local'

