version: '2'

services:
   db:
     image: mysql:latest
     volumes:
       - ./db_data1:/var/lib/mysql
     #restart: always
     env_file:  .env
     networks:
       - default
   app:
     depends_on:
       - db
     build: ./
     #image: wordpress:latest
     ports:
       - "9090:80"
       - "22000:22"
     #restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
     volumes:
       - ./wordpress:/var/www/html
     #  WORDPRESS_DB_PASSWORD: wordpress
     env_file:  .env
     external_links:
       - db:db
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     environment:
        PMA_HOST: db
        PMA_PORT: 3306
     ports:
         - 9091:80
     volumes:
         - phpmyadmin_data:/sessions
volumes:
    db_data:
    wordpress:
    phpmyadmin_data:

