version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/src
    working_dir: /app/src
    ports:
      - "8887:8888"
    command: jupyter-lab --ip=0.0.0.0 --port=8888 --allow-root

