version: '2'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-3.2-latest
    ports:
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env_db_mysql
      - .env_srv
    user: root
    networks:
      - zbx_net

  zabbix-web-apache-mysql:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-3.2-latest
    build: .
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env_db_mysql
      - .env_web
    user: root
    networks:
      - zbx_net

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-3.2-latest
    ports:
      - "10050:10050"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env_agent
    user: root
    privileged: true
    pid: "host"
    networks:
      zbx_net:
        ipv4_address: 172.16.238.5

  mysql-server:
    image: mysql:5.7
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- ./db:/var/lib/mysql
    env_file:
      - .env_db_mysql
    user: root
    networks:
      - zbx_net

networks:
  zbx_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1