version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./html/$PROJECT_NAME:/var/www/html
    ports:
      - "4000:80"
      - "4001:8000"
    tty: true
    command: ["sh", "-c", "php artisan serve --host 0.0.0.0 --port 8000"]
    env_file: .env
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 23306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin-session:/sessions
volumes:
  db:
