version: "2"
services:
  app:
    image: php7
    build:
      context: .
      dockerfile: Dockerfile-php
      args:
        PROJECT_NAME: $PROJECT_NAME
    volumes:
      - ./html:/var/www/html
    ports:
      - "4000:80"
      - "4001:8000"
    tty: true
    working_dir: /var/www/html/${PROJECT_NAME}
    command: ["sh", "-c", "php artisan serve --host 0.0.0.0 --port 8000"]
    env_file: .env
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
    env_file:
      .env_db
    ports:
      - 23306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin-session:/sessions
volumes:
  db:
